#!/bin/bash
set -e

if [  "${UPDATE_BLACKLIST_URL}" != "" ]; then
	sudo wget -O backlist.tar.gz ${UPDATE_BLACKLIST_URL} \
 		&& tar -xzf backlist.tar.gz -C /var/lib/squidguard/db \
 		&& rm backlist.tar.gz \
 		&& chown proxy:proxy /var/lib/squidguard/db -R
fi

echo "Setting correct permissions"
chown -R proxy:proxy /var/lib/squidguard/db /sample-configs /custom-config /var/log/squid3

if [ ! -f /etc/squidguard/squidGuard.conf ]; then
	# if this file doesn't exist -> it is the first time
	if [  "${SQUID_UID}" != "" ]; then
		# workaround for mac os mapping problem:
		sudo usermod -u ${SQUID_UID} proxy
	fi

	if [ "${UPDATE_BLACKLIST_URL}" != "" ]; then
	    echo "no configuration found -> use /sample-configs/bl-squidGuard.conf"
		cp -a /sample-configs/bl-squidGuard.conf /etc/squidguard/squidGuard.conf
	else
	    echo "no configuration found -> use /sample-configs/simple-squidGuard.conf"
		cp -a /sample-configs/simple-squidGuard.conf /etc/squidguard/squidGuard.conf
	fi
fi

echo "running startSquidGuard"

# run original squid start script
exec /sbin/entrypoint.sh
